# Generated by Django 2.1 on 2018-09-04 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Nombre del evento')),
                ('number_book', models.IntegerField(verbose_name='Numero de talonario')),
                ('number_bill', models.IntegerField(verbose_name='Numero de factura')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de fotos')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('person', models.OneToOneField(on_delete='Cliente', to='person.Person')),
                ('seller', models.OneToOneField(on_delete='Vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
