# Generated by Django 2.1 on 2018-09-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
