# Generated by Django 2.1 on 2018-09-04 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20180904_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
