# Generated by Django 2.1 on 2018-09-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefono')),
                ('payment', models.DecimalField(decimal_places=10, max_digits=100, verbose_name='Abono')),
                ('career', models.CharField(max_length=255, null=True, verbose_name='Carrera-Especialidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
